services:
  - type: web
    name: chatify-app
    runtime: node
    plan: free
    buildCommand: npm --prefix frontend install && npm --prefix frontend run build && npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
